In [40]:
import numpy as np
import scipy
import time

In [78]:
def rsvd(A, rank, verbose=False):
    m, n = A.shape
    transpose = False
    if m < n:
        m, n = n, m
        A = A.T
        transpose = True
    if not rank:
        rank = n
    if verbose:
        print(A.shape, transpose, m, n, rank)
    
    random = np.random.rand(n, rank)
    Q, R = np.linalg.qr(A @ random)
    if verbose:
        print(Q.shape, R.shape)
        
    U, s, V = np.linalg.svd(Q.T @ A, full_matrices=False)
    U = Q @ U
    if verbose:
        print(U.shape, s.shape, V.shape)
        
    if transpose:
        return V.T, s, U.T
    return U, s, V

In [79]:
n_cols = 4
n_rows = 4
matrix = np.array([[i + j for i in range(n_cols)] for j in range(n_rows)])
print(matrix)
print(matrix.shape)
U, s, V = rsvd(matrix, 2)
print((U * s) @ V - matrix)

[[0 1 2 3]
 [1 2 3 4]
 [2 3 4 5]
 [3 4 5 6]]
(4, 4)
[[ 2.02961807e-15  1.77635684e-15  4.44089210e-16  0.00000000e+00]
 [-2.88657986e-15  4.44089210e-16  3.10862447e-15  5.32907052e-15]
 [ 0.00000000e+00  4.44089210e-16 -4.44089210e-16 -8.88178420e-16]
 [-8.88178420e-16  8.88178420e-16  0.00000000e+00  8.88178420e-16]]


In [80]:
n_cols = 1000
n_rows = 1000
matrix = np.array([[(i + j)*1.0 for i in range(n_cols)] for j in range(n_rows)])
print(matrix.shape)
U, s, V = rsvd(matrix, 10)
st = time.time()
print('rsvd time =', time.time() - st)
print('rsvd error =', np.linalg.norm((U * s) @ V - matrix))
st = time.time()
_ = np.linalg.svd(matrix)
print('np.linalg.svd time =', time.time() - st)
st = time.time()
_ = scipy.sparse.linalg.svds(matrix, k=10)
print('scipy.sparse.linalg.svds =', time.time() - st)

(1000, 1000)
rsvd time = 2.002716064453125e-05
rsvd error = 3.19388612160583e-09
np.linalg.svd time = 0.2980070114135742
scipy.sparse.linalg.svds = 0.04700803756713867


In [81]:
n_cols = 1000
n_rows = 1000
matrix = np.array([[np.sin(i + j) for i in range(n_cols)] for j in range(n_rows)])
print(matrix.shape)
st = time.time()
U, s, V = rsvd(matrix, 2)
print('rsvd time =', time.time() - st)
print('rsvd error =', np.linalg.norm((U * s) @ V - matrix))
st = time.time()
_ = np.linalg.svd(matrix)
print('np.linalg.svd time =', time.time() - st)
st = time.time()
_ = scipy.sparse.linalg.svds(matrix, k=2)
print('scipy.sparse.linalg.svds =', time.time() - st)

(1000, 1000)
rsvd time = 0.0012340545654296875
rsvd error = 3.785541571400418e-12
np.linalg.svd time = 0.29467201232910156
scipy.sparse.linalg.svds = 0.011233091354370117


In [84]:
n_cols = 1000
n_rows = 500
matrix = np.array([[(i + j)*1.0 for i in range(n_cols)] for j in range(n_rows)])
print(matrix.shape)
U, s, V = rsvd(matrix, 10)
st = time.time()
print('rsvd time =', time.time() - st)
print('rsvd error =', np.linalg.norm((U * s) @ V - matrix))
st = time.time()
_ = np.linalg.svd(matrix)
print('np.linalg.svd time =', time.time() - st)
st = time.time()
_ = scipy.sparse.linalg.svds(matrix, k=10)
print('scipy.sparse.linalg.svds =', time.time() - st)

(500, 1000)
rsvd time = 2.09808349609375e-05
rsvd error = 1.701682797807732e-09
np.linalg.svd time = 0.1624000072479248
scipy.sparse.linalg.svds = 0.004601955413818359


In [83]:
n_cols = 500
n_rows = 1000
matrix = np.array([[(i + j)*1.0 for i in range(n_cols)] for j in range(n_rows)])
print(matrix.shape)
U, s, V = rsvd(matrix, 10)
st = time.time()
print('rsvd time =', time.time() - st)
print('rsvd error =', np.linalg.norm((U * s) @ V - matrix))
st = time.time()
_ = np.linalg.svd(matrix)
print('np.linalg.svd time =', time.time() - st)
st = time.time()
_ = scipy.sparse.linalg.svds(matrix, k=10)
print('scipy.sparse.linalg.svds =', time.time() - st)

(1000, 500)
rsvd time = 2.2649765014648438e-05
rsvd error = 2.0340375531710603e-09
np.linalg.svd time = 0.29000091552734375
scipy.sparse.linalg.svds = 0.10236167907714844
